# SPDX-License-Identifier: AGPL-3.0-or-later
name: Gemini-Nano
channels:
  - conda-forge
  - nodefaults
  - pytorch
dependencies:
  - python
  - pip
  - safetensors
  - matplotlib
  - tensorflow
  - transformers
  - sentencepiece-python
  - flatbuffers>=24.3
  - protobuf==4.25.*
  - libprotobuf==4.25.*
  - pip:
    - mediapipe