# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class BidirectionalSequenceRNNOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BidirectionalSequenceRNNOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBidirectionalSequenceRNNOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BidirectionalSequenceRNNOptionsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x46\x4C\x33", size_prefixed=size_prefixed)

    # BidirectionalSequenceRNNOptions
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BidirectionalSequenceRNNOptions
    def TimeMajor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # BidirectionalSequenceRNNOptions
    def FusedActivationFunction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # BidirectionalSequenceRNNOptions
    def MergeOutputs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # BidirectionalSequenceRNNOptions
    def AsymmetricQuantizeInputs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def BidirectionalSequenceRNNOptionsStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    BidirectionalSequenceRNNOptionsStart(builder)

def BidirectionalSequenceRNNOptionsAddTimeMajor(builder: flatbuffers.Builder, timeMajor: bool):
    builder.PrependBoolSlot(0, timeMajor, 0)

def AddTimeMajor(builder: flatbuffers.Builder, timeMajor: bool):
    BidirectionalSequenceRNNOptionsAddTimeMajor(builder, timeMajor)

def BidirectionalSequenceRNNOptionsAddFusedActivationFunction(builder: flatbuffers.Builder, fusedActivationFunction: int):
    builder.PrependInt8Slot(1, fusedActivationFunction, 0)

def AddFusedActivationFunction(builder: flatbuffers.Builder, fusedActivationFunction: int):
    BidirectionalSequenceRNNOptionsAddFusedActivationFunction(builder, fusedActivationFunction)

def BidirectionalSequenceRNNOptionsAddMergeOutputs(builder: flatbuffers.Builder, mergeOutputs: bool):
    builder.PrependBoolSlot(2, mergeOutputs, 0)

def AddMergeOutputs(builder: flatbuffers.Builder, mergeOutputs: bool):
    BidirectionalSequenceRNNOptionsAddMergeOutputs(builder, mergeOutputs)

def BidirectionalSequenceRNNOptionsAddAsymmetricQuantizeInputs(builder: flatbuffers.Builder, asymmetricQuantizeInputs: bool):
    builder.PrependBoolSlot(3, asymmetricQuantizeInputs, 0)

def AddAsymmetricQuantizeInputs(builder: flatbuffers.Builder, asymmetricQuantizeInputs: bool):
    BidirectionalSequenceRNNOptionsAddAsymmetricQuantizeInputs(builder, asymmetricQuantizeInputs)

def BidirectionalSequenceRNNOptionsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return BidirectionalSequenceRNNOptionsEnd(builder)
