# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class BidirectionalSequenceLSTMOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BidirectionalSequenceLSTMOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBidirectionalSequenceLSTMOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BidirectionalSequenceLSTMOptionsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x46\x4C\x33", size_prefixed=size_prefixed)

    # BidirectionalSequenceLSTMOptions
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BidirectionalSequenceLSTMOptions
    def FusedActivationFunction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # BidirectionalSequenceLSTMOptions
    def CellClip(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BidirectionalSequenceLSTMOptions
    def ProjClip(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BidirectionalSequenceLSTMOptions
    def MergeOutputs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # BidirectionalSequenceLSTMOptions
    def TimeMajor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # BidirectionalSequenceLSTMOptions
    def AsymmetricQuantizeInputs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def BidirectionalSequenceLSTMOptionsStart(builder: flatbuffers.Builder):
    builder.StartObject(6)

def Start(builder: flatbuffers.Builder):
    BidirectionalSequenceLSTMOptionsStart(builder)

def BidirectionalSequenceLSTMOptionsAddFusedActivationFunction(builder: flatbuffers.Builder, fusedActivationFunction: int):
    builder.PrependInt8Slot(0, fusedActivationFunction, 0)

def AddFusedActivationFunction(builder: flatbuffers.Builder, fusedActivationFunction: int):
    BidirectionalSequenceLSTMOptionsAddFusedActivationFunction(builder, fusedActivationFunction)

def BidirectionalSequenceLSTMOptionsAddCellClip(builder: flatbuffers.Builder, cellClip: float):
    builder.PrependFloat32Slot(1, cellClip, 0.0)

def AddCellClip(builder: flatbuffers.Builder, cellClip: float):
    BidirectionalSequenceLSTMOptionsAddCellClip(builder, cellClip)

def BidirectionalSequenceLSTMOptionsAddProjClip(builder: flatbuffers.Builder, projClip: float):
    builder.PrependFloat32Slot(2, projClip, 0.0)

def AddProjClip(builder: flatbuffers.Builder, projClip: float):
    BidirectionalSequenceLSTMOptionsAddProjClip(builder, projClip)

def BidirectionalSequenceLSTMOptionsAddMergeOutputs(builder: flatbuffers.Builder, mergeOutputs: bool):
    builder.PrependBoolSlot(3, mergeOutputs, 0)

def AddMergeOutputs(builder: flatbuffers.Builder, mergeOutputs: bool):
    BidirectionalSequenceLSTMOptionsAddMergeOutputs(builder, mergeOutputs)

def BidirectionalSequenceLSTMOptionsAddTimeMajor(builder: flatbuffers.Builder, timeMajor: bool):
    builder.PrependBoolSlot(4, timeMajor, 1)

def AddTimeMajor(builder: flatbuffers.Builder, timeMajor: bool):
    BidirectionalSequenceLSTMOptionsAddTimeMajor(builder, timeMajor)

def BidirectionalSequenceLSTMOptionsAddAsymmetricQuantizeInputs(builder: flatbuffers.Builder, asymmetricQuantizeInputs: bool):
    builder.PrependBoolSlot(5, asymmetricQuantizeInputs, 0)

def AddAsymmetricQuantizeInputs(builder: flatbuffers.Builder, asymmetricQuantizeInputs: bool):
    BidirectionalSequenceLSTMOptionsAddAsymmetricQuantizeInputs(builder, asymmetricQuantizeInputs)

def BidirectionalSequenceLSTMOptionsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return BidirectionalSequenceLSTMOptionsEnd(builder)
