# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class IfOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IfOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIfOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def IfOptionsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x46\x4C\x33", size_prefixed=size_prefixed)

    # IfOptions
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IfOptions
    def ThenSubgraphIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # IfOptions
    def ElseSubgraphIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def IfOptionsStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    IfOptionsStart(builder)

def IfOptionsAddThenSubgraphIndex(builder: flatbuffers.Builder, thenSubgraphIndex: int):
    builder.PrependInt32Slot(0, thenSubgraphIndex, 0)

def AddThenSubgraphIndex(builder: flatbuffers.Builder, thenSubgraphIndex: int):
    IfOptionsAddThenSubgraphIndex(builder, thenSubgraphIndex)

def IfOptionsAddElseSubgraphIndex(builder: flatbuffers.Builder, elseSubgraphIndex: int):
    builder.PrependInt32Slot(1, elseSubgraphIndex, 0)

def AddElseSubgraphIndex(builder: flatbuffers.Builder, elseSubgraphIndex: int):
    IfOptionsAddElseSubgraphIndex(builder, elseSubgraphIndex)

def IfOptionsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return IfOptionsEnd(builder)
