# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class Pool2DOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Pool2DOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPool2DOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def Pool2DOptionsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x46\x4C\x33", size_prefixed=size_prefixed)

    # Pool2DOptions
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Pool2DOptions
    def Padding(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Pool2DOptions
    def StrideW(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Pool2DOptions
    def StrideH(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Pool2DOptions
    def FilterWidth(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Pool2DOptions
    def FilterHeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Pool2DOptions
    def FusedActivationFunction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def Pool2DOptionsStart(builder: flatbuffers.Builder):
    builder.StartObject(6)

def Start(builder: flatbuffers.Builder):
    Pool2DOptionsStart(builder)

def Pool2DOptionsAddPadding(builder: flatbuffers.Builder, padding: int):
    builder.PrependInt8Slot(0, padding, 0)

def AddPadding(builder: flatbuffers.Builder, padding: int):
    Pool2DOptionsAddPadding(builder, padding)

def Pool2DOptionsAddStrideW(builder: flatbuffers.Builder, strideW: int):
    builder.PrependInt32Slot(1, strideW, 0)

def AddStrideW(builder: flatbuffers.Builder, strideW: int):
    Pool2DOptionsAddStrideW(builder, strideW)

def Pool2DOptionsAddStrideH(builder: flatbuffers.Builder, strideH: int):
    builder.PrependInt32Slot(2, strideH, 0)

def AddStrideH(builder: flatbuffers.Builder, strideH: int):
    Pool2DOptionsAddStrideH(builder, strideH)

def Pool2DOptionsAddFilterWidth(builder: flatbuffers.Builder, filterWidth: int):
    builder.PrependInt32Slot(3, filterWidth, 0)

def AddFilterWidth(builder: flatbuffers.Builder, filterWidth: int):
    Pool2DOptionsAddFilterWidth(builder, filterWidth)

def Pool2DOptionsAddFilterHeight(builder: flatbuffers.Builder, filterHeight: int):
    builder.PrependInt32Slot(4, filterHeight, 0)

def AddFilterHeight(builder: flatbuffers.Builder, filterHeight: int):
    Pool2DOptionsAddFilterHeight(builder, filterHeight)

def Pool2DOptionsAddFusedActivationFunction(builder: flatbuffers.Builder, fusedActivationFunction: int):
    builder.PrependInt8Slot(5, fusedActivationFunction, 0)

def AddFusedActivationFunction(builder: flatbuffers.Builder, fusedActivationFunction: int):
    Pool2DOptionsAddFusedActivationFunction(builder, fusedActivationFunction)

def Pool2DOptionsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Pool2DOptionsEnd(builder)
