# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class WhileOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WhileOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWhileOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def WhileOptionsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x46\x4C\x33", size_prefixed=size_prefixed)

    # WhileOptions
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WhileOptions
    def CondSubgraphIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # WhileOptions
    def BodySubgraphIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def WhileOptionsStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    WhileOptionsStart(builder)

def WhileOptionsAddCondSubgraphIndex(builder: flatbuffers.Builder, condSubgraphIndex: int):
    builder.PrependInt32Slot(0, condSubgraphIndex, 0)

def AddCondSubgraphIndex(builder: flatbuffers.Builder, condSubgraphIndex: int):
    WhileOptionsAddCondSubgraphIndex(builder, condSubgraphIndex)

def WhileOptionsAddBodySubgraphIndex(builder: flatbuffers.Builder, bodySubgraphIndex: int):
    builder.PrependInt32Slot(1, bodySubgraphIndex, 0)

def AddBodySubgraphIndex(builder: flatbuffers.Builder, bodySubgraphIndex: int):
    WhileOptionsAddBodySubgraphIndex(builder, bodySubgraphIndex)

def WhileOptionsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return WhileOptionsEnd(builder)
